### PR TITLE
Support adding Reviewers or Assignees by email instead of an Id

### PR DESCRIPTION
**Pull request by BobSilent**
The current configuration for Reviewers or Assignees is quite cumbersome. 
As described in #543 required to configure some cryptic ID numbers in the `dependabot.yml`.

This PR enables the configuration of email addresses, which is much more aligned with the dependabot [config description](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#assignees).

this now allows the configuration:
```
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    # Add assignees
    assignees:
      - "alice@example.com"
      - "bob@example.com"
``` 

internally the email addresses are resolved and the ids are passed to dependabot for creating the PR.

### CODE REVIEW

**Comment by mburumaxwell** [comment]
1. I don't think there's a need to change the updater. The extension can fetch the user identifier from the API and form a JSON array as is expected. That way it doesn't break current functionality.
2. I'd rather check each entry to find if it is an email (e.g. check it contains an `@`) to determine if it is an email or an ID. You could choose to do the reverse by parsing as a GUID.
3. The changes need to be effected server side too.
4. Please add tests for the changes unless.

**Comment by BobSilent** [comment]
I will look into it
1. is mainly for logging the Reviewers and Assignees in clear text, but can be omitted.
2. how would you do that? Via [regular expression ](https://stackoverflow.com/a/13653180/20598378)? I wanted to make it fast (faster than regex) and the "fallback" is always assumed as a UUID no `@` should be part of it, [see here](https://github.com/tinglesoftware/dependabot-azure-devops/blob/25401204699dd34ba86fcca8c54da4411e6e43ad/extension/task/utils/resolveAzureDevOpsIdentities.ts#L34-L42).
3. I did not got this point, which changes needs to be done server side? Can you give me a hint here?
4. Which parts would you focus on in the tests? The point that emails are handled differently that other input strings?

**Comment by BobSilent** [comment]
@mburumaxwell did you had a chance to review this?

**Comment by mburumaxwell** [comment]
@BobSilent could you resolve the conflict so I can merge?

**Comment by BobSilent** [comment]
Sure, I will take care here.

**Comment by BobSilent** [comment]
@mburumaxwell: rebased the PR

**Review by mburumaxwell — APPROVED** [review]

**Comment by semkeijsper** [comment]
As soon as I add a `reviewers` or `assignees` field in my config, my pipeline throws: "##[error]Cannot read properties of undefined (reading 'length')".

this is my pipeline:
```yml
trigger: none # Disable CI trigger

schedules:
  - cron: '0 2 * * *' # daily at 2am UTC
    always: true # run even when there are no code changes
    branches:
      include:
        - master
    batch: true
    displayName: Daily

stages:
  - stage: CheckDependencies
    displayName: 'Check Dependencies'
    jobs:
      - job: Dependabot
        displayName: 'Run Dependabot'
        pool:
          vmImage: 'ubuntu-latest' # Only Ubuntu and MacOS is supported at this time
        steps:
          - task: dependabot@1
            displayName: 'Run Dependabot'
```

and my `dependabot.yml`:
```yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
    reviewers:
      - "<email>"
```

Any idea what could be going wrong?

**Pull request merged**
