### PR TITLE
Enable Auto-Approve of PRs

### PR DESCRIPTION
**Pull request by huserben**
Enable Auto-Approve for specified users as described in #95 

Extend script to handle 3 additional parameters:
- _AZURE_AUTO_APPROVE_PR_ to enable/disable auto-approval
- _AZURE_AUTO_APPROVE_NAME_ to specify the email address of the user that shall used for approval (as far as I found the build service user cannot approve)
- _AZURE_AUTO_APPROVE_TOKEN_ to specify the PAT of the user that is used to approve (the request to approve a PR must be made with a PAT from the user that approves)

Extend task to take the three additional inputs from above.

Tested locally with a docker image with following command:
`docker run --rm -i -e AZURE_HOSTNAME=dev.azure.com -e AZURE_ACCESS_TOKEN=*** -e AZURE_ORGANIZATION=huserben -e AZURE_PROJECT=DependabotTest -e AZURE_REPOSITORY=DependabotTest -e DEPENDABOT_PACKAGE_MANAGER=nuget -e DEPENDABOT_DIRECTORY=/ConsoleApp1 -e DEPENDABOT_VERSIONING_STRATEGY=auto -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=5 -e AZURE_AUTO_APPROVE_PR=true -e AZURE_AUTO_APPROVE_TOKEN=*** -e AZURE_AUTO_APPROVE_NAME=benjamin.m.huser@gmail.com docker.io/huserben/dependabotazuredevops:latest`

where it worked successfully.
However I could **not test** it with the task directly in Azure DevOps. Before a new version is created we should try this out on Azure DevOps and with the build service account to make sure it works as expected.

Today was the first I wrote ruby code so I'm happy for any kind of feedback you have.

### CODE REVIEW

**Comment by mburumaxwell** [comment]
@huserben This looks really great. Just a few comments/questions:

1. Could it be better/clearer to rename `AZURE_AUTO_APPROVE_USER` to `AZURE_AUTO_APPROVE_USER_EMAIL` and `AZURE_AUTO_APPROVE_TOKEN` to `AZURE_AUTO_APPROVE_USER_TOKEN` for the docker environment variables?
2. Could it be better/clearer to rename `azureAutoApproveUser` to `azureAutoAprooveUserEmail` and `azureAutoApproveToken` to `azureAutoApproveUserToken` for the task inputs?
3. Could it be better/clearer to rename the put method in `azure_helpers.rb` to `put_with_token` so that there's a clear difference from the one in the upstream implementation?
4. How to handle approval by the same user who is creating the Pull Requests? (token already provided)

All in all, this is a great contribution. The best I've seen so far.

**Comment by huserben** [comment]
@mburumaxwell thanks for the feedback.
1-3 I'll take up once I get to it and will also test it on Azure Devops (probably the weekend).

For 4 I'm not sure. The approval is a bit tricky, as we need to somehow fetch this id, and it's currently done via the email. What we could do is reuse the already provided token if AZURE_AUTO_APPROVE_USER_TOKEN is not set. However the email still must be set in order to fetch this id (unless there is a different way, but I have not seen it). What doesn't work as far as I know is to approve with the service user.
What I was wondering is whether this is even needed anyway, If the same person approves that creates it, there might not be any policy in place anyway, so maybe the auto-approve is not needed and the PR will complete just by setting auto-complete to true...

**Comment by huserben** [comment]
@mburumaxwell 

I Implemented the changes you proposed. I also added the handling that we're reusing the AZURE_ACCESS_TOKEN if there's no AZURE_AUTO_APPROVE_USER_TOKEN specified.

Also tried it on my DevOps and it works smoothly.

One remaining question I had was about whether we must change the version of the docker image tag, and bump it to 0.4:
```
      // Allow overriding of the docker image tag globally
      let dockerImageTag: string = tl.getVariable("DEPENDABOT_DOCKER_IMAGE_TAG");
      if (!dockerImageTag) {
        dockerImageTag = "0.3"; // will pull the latest patch for 0.3 e.g. 0.3.0
      }
```

**Comment by mburumaxwell** [comment]
@huserben 

This looks okay. I will proceed and merge once the actions succeed. Regarding the version (`dockerImageTag`), I usually update just before making a release.

**Pull request merged**
