### PR TITLE
Add support for ignore conditions using .github/dependabot.yml file.

### PR DESCRIPTION
**Pull request by assi010**
Currently the ignore value ([docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore)) is not being read from the .github/dependabot.yml file.

I updated the extension so that this value will now be used to set the DEPENDABOT_IGNORE_CONDITIONS environment variable.

### CODE REVIEW

**Comment by mburumaxwell** [comment]
@assi010 the ignore conditions are automatically picked up from the configuration file in the ruby script.

See https://github.com/tinglesoftware/dependabot-azure-devops/blob/8a11e4281a521a41c8f45b2560cf17f048d62cdf/updater/bin/update-script.rb#L468-L497

and also

https://github.com/tinglesoftware/dependabot-azure-devops/blob/8a11e4281a521a41c8f45b2560cf17f048d62cdf/updater/bin/update-script.rb#L272-L292

**Comment by assi010** [comment]
Thanks for explaining @mburumaxwell. 

I used the Azure Devops extension with the following dependabot.yml configuration:
```yaml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
```

However, it would still create pull requests for packages updating them from version 6.x.x to 7.x.x. After adding the `DEPENDABOT_IGNORE_CONDITIONS` environment variable the issue was resolved, which lead to creating this PR. 

I'll do another check just to be sure I didn't misconfigure anything on my end.

**Comment by DaleMckeown** [comment]
@assi010 I've definitely had semver blocking working before, infact it was the only way I could figure out how to do it until I finally cracked how to do it with versions specifically.

This was previously working for me:

```
    - dependency-name: 'Microsoft.EntityFrameworkCore.Relational'
       update-types: ['version-update:semver-major']
```

I suspect that the `dependency-name` being a wildcard might be the problem. As a test, you could try targeting a package or two explicitly, and see what happens.

The issue i opened on dependabot core is here: https://github.com/dependabot/dependabot-core/issues/6873

**Comment by assi010** [comment]
@DaleMckeown I'll definitely try that, thanks for the suggestion! 

But isn't it weird that the extension sets all values it parses from `dependabot.yml` as environment variables to the docker image, yet it omits the ignore conditions?

image

Allow conditions and ignore conditions are both optional with a JSON value according to the docs in this repo.

https://github.com/tinglesoftware/dependabot-azure-devops/blob/8a11e4281a521a41c8f45b2560cf17f048d62cdf/extension/task/utils/parseConfigFile.ts#L176 

Here the allow value is parsed from the config file by the extension.

https://github.com/tinglesoftware/dependabot-azure-devops/blob/8a11e4281a521a41c8f45b2560cf17f048d62cdf/extension/task/index.ts#L96-L99

And here it is used to set as environment variable for the docker image. 

The ignore conditions are never set. However, when I set them as the environment variable everything worked as expected.

In the documentation of dependabot it even gives `dependency-name: "*"` as a valid example:

image

Considering it works with the environment variable and that the example configuration is valid according to the docs, I am a little skeptical that this is really the issue.

**Comment by mburumaxwell** [comment]
`DEPENDABOT_IGNORE_CONDITIONS` is only meant to override, and currently a remnant of when we did not have proper support for the configuration file. `DEPENDABOT_ALLOW_CONDITIONS` exists because the upstream currently does not have a similar concept. Nothing wrong or odd with that.

That said, I just pulled a configuration file from one of our projects that uses ignores, wildcards, and I know it works because I wrote it:

```yml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: "nuget" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "daily"
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  # Ignore patch updates for some packages
  - dependency-name: "Microsoft.*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: "System.*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: "MongoDB.*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: "Moq"
    update-types: ["version-update:semver-patch"]
```

But for clarity sake, I have created a repro from what you provided. The package does not get updated.
- Repository: https://dev.azure.com/tingle/dependabot/_git/repro-582
- Pipeline run: https://dev.azure.com/tingle/dependabot/_build/results?buildId=57486&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1f93c1a3-255b-505a-53c9-c382114aabf5

Did I miss anything?

**Comment by assi010** [comment]
Thanks for the provided repro, it finally led me to the real issue at play here. 

I looked at your project and tried to reproduce it in my own Azure Devops project once again, however this time it worked perfectly. I thought I was losing my mind..

I compared my previous repro project and the current one. On my Windows machine the `dependabot.yml` was created as UTF-8 BOM, while on my linux machine it was created as UTF-8.

Turns out that on the UTF-8 BOM version the ignore conditions are not picked up properly, while it works fine on UTF-8. That is why I started looking into the environment variables, as it worked completely fine when using the environment variables together with UTF-8 BOM.

Change:
image


Pipeline with `dependabot.yml` as UTF-8
image

Pipeline with `dependabot.yml` as UTF-8 BOM
image

After removing the BOM from my `dependabot.yml` in my existing project, the conditions are picked up as expected as you can see. 

Sorry for insisting on my changes @mburumaxwell @DaleMckeown, turns out my "fix" was just a workaround for a whole other issue :sweat_smile:. Thanks for the help.

**Comment by mburumaxwell** [comment]
I doubt these are as related. Maybe if your pipeline has other things going on.
Glad it's working now.

**Comment by assi010** [comment]
> I doubt these are as related. Maybe if your pipeline has other things going on. Glad it's working now.

That makes sense, but I am able to consistently reproduce the issue with your example using Azure hosted agents.
Just remove the top 5 lines of your `dependabot.yml` so that it starts with the version line at the top, add BOM and it will stop ignoring version 7.x.x updates.

**Comment by mburumaxwell** [comment]
This is a curious case. It could either be the BOM or the comments.

**Comment by mburumaxwell** [comment]
Possibly related to https://github.com/dependabot/dependabot-core/pull/6714

**Comment by jump912** [comment]
Hey guys. I am using Azure devops. the dependabot is set through azure pipeline task, and the docker image repo is set to tinglesoftware/dependabot-updater. I have a problem ignoring package from creating PR.

I have configured the dependabot.yml as below.
image

when ran in pipeline, it is still trying to create PR for it. I tried both using wildcard and exact name for the dependency name.
image

**Pull request closed without merging**
