### PR TITLE
Bug/auto complete pr ado 2019

### LINKED ISSUE #288: Pull requests not auto-completing in ADO 2019
The pull request auto-complete feature currently does not work with the dependabot script if using ADO 2019.

### PR DESCRIPTION
**Pull request by PatrickBig**
Fixes #288 

Based on the REST API versioning document from Microsoft ADO 2019 only supports API versions of <= 5.0
https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops

By bumping the API version down to 5.0 in the script it should allow auto-completing PRs.

There is still some v6 usage in the current version of the task but that is outside of the scope of what I'm trying to address with this PR.

### CODE REVIEW

**Comment by mburumaxwell** [comment]
@PatrickBig thanks for this contribution. I will proceed and merge. However, instead of changing the value for everyone, I will make the apiVersion a task input whose value can then be used in all custom endpoint.

**Comment by shtlrs** [comment]
@PatrickBig We're currently using Version Dev19.M208.1 of ADO, and the PR doesn't auto-complete still :/

@mburumaxwell has the `apiVersion` input PR been submitted & merged?

**Comment by shtlrs** [comment]
So I updated the image to be pulled to 0.8, and the PR doesn't autocomplete.

**Comment by mburumaxwell** [comment]
@shtlrs  which input are you referring to? Did you make a PR?

**Comment by shtlrs** [comment]
> @PatrickBig thanks for this contribution. I will proceed and merge. However, instead of changing the value for everyone, I will make the apiVersion a task input whose value can then be used in all custom endpoints in a later PR.

@mburumaxwell  I was referring to you saying that you'll `make the apiVersion a task input whose value can then be used in all custom endpoints`

**Pull request merged**
