### PR TITLE
Allow customizing of dependabot author email/name

### PR DESCRIPTION
**Pull request by BobSilent**
With default configuration the commit is authored with email `noreply@github.com` 
in our ADO Server (OnPrem) installation there is no account with this email, therefore the commit cannot be linked with an ADO account and no profile Icon is shown.
Whereas the PR is correctly linked with the Account:

image

This PR allows the configuration of the committer author email and account, with these variables
```env
GIT_AUTHOR_EMAIL=myemail@provider.com
GIT_AUTHOR_NAME=ownname
```
within the pipeline task `extraEnvironmentVariables`

### CODE REVIEW

**Comment by mburumaxwell** [comment]
@BobSilent , thanks for your contribution. I see it only affects the ruby script. Do you only use the docker image or do you also use the extension. If you use the extension, the env variables need to passed over from the extension (written in typescript) to the container.

**Comment by BobSilent** [comment]
I am using both, extension + docker image - many thanks for this project here!!

I have all the PRs integrated in a (currently) private image incl. private extension.
I am currently providing the environment variables to the extension within yaml pipeline

```yaml
steps:
- task: dependabot@1
  inputs:
    useConfigFile: true
    setAutoComplete: true
    mergeStrategy: '2'
    azureDevOpsAccessToken: '$(DEPENDABOT_ADO_PAT)'
    extraEnvironmentVariables: GIT_AUTHOR_EMAIL=myemail@provider.com;GIT_AUTHOR_NAME=dependabot;WORKAROUND_CMD=sed -i 1' s/^/#/' /etc/resolv.conf
    dockerImageRepository: '$(DEPENDABOT_DOCKER_IMAGE_NAME)'
    dockerImageTag: '$(DEPENDABOT_DOCKER_IMAGE_VERSION)'
```

maybe it makes sense to add an information to the `README.md`?

**Comment by mburumaxwell** [comment]
This makes sense. I totally forgot `extraEnvironmentVariables` input existed.
There may be no need to add these to the extension task just to keep it simple. Fewer configuration options mean a smother start.

Indeed, the new ENV variables should be described in the README.md file like all the others at https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/src/script/README.md

With that I can do the merge.

**Comment by mburumaxwell** [comment]
Happy to see another user with a dedicated dependabot account. Will now merge.

**Pull request merged**
