### PR TITLE
Allow Usage of Basic-Auth

### PR DESCRIPTION
**Pull request by WebsiteDeveloper**
Allow Usage of Basic-Auth by setting AZURE_ACCESS_USERNAME variable

When Token is set to Password basic auth is used.

### CODE REVIEW

**Comment by mburumaxwell** [comment]
This removes support for PATs

**Comment by WebsiteDeveloper** [comment]
> This removes support for PATs

I am not that well versed in ruby as i understood it if the environment variable is empty the fallback for the PAT Token is used.
Could you point me in the right direction?

**Comment by WebsiteDeveloper** [comment]
Is my assumption wrong? @mburumaxwell

**Comment by mburumaxwell** [comment]
@WebsiteDeveloper are you using plain Docker, running on Kubernetes or using the extension?

**Comment by WebsiteDeveloper** [comment]
We are using the extension.
For testing the changes i used a locally built docker container

**Comment by mburumaxwell** [comment]
Happy that you tested locally with Docker.

For the extension, you also need a username input which is passed to the container as an environment variable.

**Comment by WebsiteDeveloper** [comment]
@mburumaxwell i added some more changes
Which should now enable the setting in the extension

**Comment by WebsiteDeveloper** [comment]
Could i get some feedback on the proposed changes?

**Comment by WebsiteDeveloper** [comment]
I would really be happy to make the necessary change but i am gonna need a bit more guidance

**Comment by mburumaxwell** [comment]
@WebsiteDeveloper 
Thanks for your contribution.

**Pull request merged**
